version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: miga_personalizados_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: miga_personalizados
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d miga_personalizados"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: miga_personalizados_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - DB_DATABASE=miga_personalizados
      - JWT_SECRET=your_super_secret
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: miga_personalizados_frontend
    restart: always
    ports:
      - "5174:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
